name: Mixed Unit Tests (All Frameworks)

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Type of test to run'
        required: false
        default: 'all'
        type: choice
        options:
        - all
        - java
        - python
        - nodejs

jobs:
  # Java JUnit Tests
  java-junit:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.test_type == 'all' || github.event.inputs.test_type == 'java' }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Run Java JUnit Tests
      run: |
        cd java-service
        mvn clean test || true
    
    - name: Upload JUnit XML Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: junit-test-results
        path: java-service/target/surefire-reports/*.xml

  # Python Pytest Tests  
  python-pytest:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.test_type == 'all' || github.event.inputs.test_type == 'python' }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install pytest
      run: pip install pytest
    
    - name: Run Python Pytest Tests
      run: |
        cd python-service
        pytest tests/ -v --tb=short || true

  # Node.js Jest Tests
  nodejs-jest:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.test_type == 'all' || github.event.inputs.test_type == 'nodejs' }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        cd node-service
        npm install
    
    - name: Run Node.js Jest Tests
      run: |
        cd node-service
        npm test || true

  # Test Summary
  test-summary:
    runs-on: ubuntu-latest
    needs: [java-junit, python-pytest, nodejs-jest]
    if: always()
    steps:
    - name: Test Results Summary
      run: |
        echo "## Mixed Unit Test Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Frameworks Tested:" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ **Java JUnit**: Mixed pass/fail results" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ **Python Pytest**: Mixed pass/fail results" >> $GITHUB_STEP_SUMMARY  
        echo "- ✅ **Node.js Jest**: Mixed pass/fail results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Each framework includes intentional test failures for testing stack trace parsing and error handling." >> $GITHUB_STEP_SUMMARY
